---
meta:
  id: 1011
  enable: true
  note: WordPress login page
trigger:
  uri: /wp-login.php
response:
  status: 200
  header:
    Set-Cookie: wordpress_test_cookie=WP+Cookie+check; path=/
  body: |
    <!DOCTYPE html>
    <!--[if IE 8]>
        <html xmlns="http://www.w3.org/1999/xhtml" class="ie8" lang="ja">
      <![endif]-->
    <!--[if !(IE 8) ]><!-->
    <html xmlns="http://www.w3.org/1999/xhtml" lang="ja">
    <!--<![endif]-->

    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      <title>blog login</title>
      <meta name='robots' content='noindex,follow' />
      <meta name="viewport" content="width=device-width" />
    </head>

    <body class="login login-action-login wp-core-ui">
      <div id="login">
        <h1>
          <a href="https://www.wordpress.org/" title="Powered by WordPress" tabindex="-1">blog</a>
        </h1>

        <form name="loginform" id="loginform" action="/wp-login.php" method="post">
          <p>
            <label for="user_login">user name or e-mail address
              <br />
              <input type="text" name="log" id="user_login" class="input" value="" size="20" />
            </label>
          </p>
          <p>
            <label for="user_pass">password
              <br />
              <input type="password" name="pwd" id="user_pass" class="input" value="" size="20" />
            </label>
          </p>
          <p class="forgetmenot">
            <label for="rememberme">
              <input name="rememberme" type="checkbox" id="rememberme" value="forever" /> remember</label>
          </p>
          <p class="submit">
            <input type="submit" name="wp-submit" id="wp-submit" class="button button-primary button-large" value="login" />
            <input type="hidden" name="redirect_to" value="/wp-admin/" />
            <input type="hidden" name="testcookie" value="1" />
          </p>
        </form>

        <p id="nav">
          <a href="/wp-login.php?action=lostpassword">lost password?</a>
        </p>

        <script type="text/javascript">
          function wp_attempt_focus() {
            setTimeout(function () {
              try {
                d = document.getElementById('user_login');
                d.focus();
                d.select();
              } catch (e) {}
            }, 200);
          }

          /**
          * Filters whether to print the call to `wp_attempt_focus()` on the login screen.
          *
          * @since 4.8.0
          *
          * @param bool $print Whether to print the function call. Default true.
          */
          wp_attempt_focus();
          if (typeof wpOnload == 'function') wpOnload();
        </script>

        <p id="backtoblog">
          <a href="/">&larr; return blog top</a>
        </p>

      </div>


      <div class="clear"></div>
    </body>

    </html>
