---
meta:
  id: 1041
  enable: true
  note: Weblogic RCE CVE-2017-10271
trigger:
  method: POST
  uri: /wls-wsat/CoordinatorPortType
response:
  status: 500
  body: |
    <?xml version='1.0' encoding='UTF-8'?>
    <S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">
      <S:Body>
        <ns0:Fault xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://www.w3.org/2003/05/soap-envelope">
          <faultcode>ns0:Client</faultcode>
          <faultstring>Couldn't create SOAP message due to exception: XML reader error: com.ctc.wstx.exc.WstxEOFException: Unexpected EOF
            in prolog&#xd; at [row,col {unknown-source}]: [1,0]</faultstring>
        </ns0:Fault>
      </S:Body>
    </S:Envelope>
