---
meta:
  id: 1042
  enable: true
  note: Weblogic login
trigger:
  uri: j_security_check
response:
  status: 200
  body: |
    <HTML> <HEAD><TITLE>Deploying Application</TITLE> <META HTTP-EQUIV="content-type" CONTENT="text/html"/><META http-equiv="Refresh" content="2" /> </HEAD> <BODY> <H2> Deploying application for /console/login/LoginForm.jsp/j_security_check... </H2> <br/> This application is deployed on the first access. You can change this application to instead deploy during startup.<br/> Refer to instructions in the On-Demand Deployment documentation. </BODY> </HTML>
