---
meta:
  id: 1001
  enable: true
  note: Login request sample(GET)
trigger:
  method: GET
  uri: /login
response:
  status: 200
  header:
    Server: Apache/2.0.48
    Content-Type: text/html
  body: |
    <html>

    <head>
      <title>login</title>
    </head>

    <body>
      <form action="/login" method="post">
        <p>
          name:
          <input type="text" id="name" />
          <br> password:
          <input type="password" id="pass" />
          <br>
          <button type="submit">login</button>
        </p>
      </form>
    </body>

    </html>
