---
meta:
  id: 1028
  enable: true
  note: JBoss
trigger:
  uri: /admin-console/
response:
  status: 200
  header:
    Server: Apache-Coyote/1.1
    X-Powered-By: Servlet/3.0; JBossAS-6
  body: |
    <?xml version="1.0" encoding="iso-8859-1"?>
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">

    <head>
      <title>Welcome to JBoss AS</title>
      <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
      <link rel="StyleSheet" href="css/jboss.css" type="text/css" />
    </head>

    <body>
      <!-- header begin -->
      <div id="header">
        <a href="http://www.jboss.org">
          <img src="images/logo.gif" alt="JBoss" id="logo" width="226" height="105" />
        </a>
      </div>
      <!-- header end -->

      <h3>Manage this JBoss AS Instance</h3>
      <ul>
        <li>
          <a href="/admin-console/">Administration Console</a>
        </li>
        <li>
          <a href="/jmx-console/">JMX Console</a>
        </li>
        <li>
          <a href="/jbossws/">JBoss Web Services Console</a>
        </li>
      </ul>
      <h3>JBoss AS Online Resources</h3>
      <ul>
        <li>
          <a href="http://www.jboss.org/jbossas/docs">JBoss AS Documentation</a>
        </li>
        <li>
          <a href="http://community.jboss.org/en/wiki">JBoss Wiki</a>
        </li>
        <li>
          <a href="http://jira.jboss.org/jira/browse/JBAS">JBoss AS JIRA</a>
        </li>
        <li>
          <a href="http://community.jboss.org/en/jbossas">JBoss Forums</a>
        </li>
        <li>
          <a href="https://lists.jboss.org/">JBoss Mailing Lists</a>
        </li>
      </ul>

      <!-- footer begin -->
      <div id="footer">
        <div id="credits">
          <a href="http://www.jboss.org/jbossas">JBoss Application Server</a>
        </div>
        <div id="footer_bar">&nbsp;</div>
      </div>
      <!-- footer end -->
    </body>

    </html>
